blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ Relatar um Bug
    file: relatar-bug.md
  - name: âœ¨ Nova Funcionalidade
    file: sugerir-funcionalidade.md
  - name: â“ DÃºvida
    file: tenho-uma-pergunta.md

