blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ Relatar um Bug
    file: bug_report.md
  - name: âœ¨ Nova Funcionalidade
    file: feature_request.md
  - name: â“ DÃºvida
    file: question.md
