blank_issues_enabled: false
contact_links: []

feature_requests_enabled: false
bug_report_contact_links: []

issue_templates:
  - name: "ğŸ Relatar um Bug"
    about: "Nos informe sobre algum bug ou problema"
    title: "[BUG] "
    labels: ["bug"]
    body: "relatar-bug.md"
  - name: âœ¨ Nova Funcionalidade
    about: "Sugira uma melhoria"
    title: "[MELHORIA] "
    labels: ["enhancement"]
    body: "sugerir-funcionalidade.md"
  - name: â“ DÃºvida
    about: "FaÃ§a uma pergunta"
    title: "[DÃšVIDA] "
    labels: ["question"]
    body: "tenho-uma-pergunta.md"

